"""Read fixtures generated by Netpbm, without requiring external tools at runtime."""

from pathlib import Path

import numpy as np
import pytest

from justpfm import read_pfm

FIXTURES = Path(__file__).parent / "fixtures" / "netpbm"


@pytest.mark.parametrize(
    "name,extension,channels", [("grayscale", "pgm", 1), ("rgb", "ppm", 3)]
)
@pytest.mark.parametrize("endian,dtype", [("little", "<f4"), ("big", ">f4")])
@pytest.mark.parametrize("scale", ["0.5", "1", "2"])
def test_read_netpbm_fixture(name, extension, channels, endian, dtype, scale):
    # The original PNM samples are a separate oracle, not decoded by justPFM.
    fields = (FIXTURES / (name + "." + extension)).read_text().split()
    width, height, maxval = map(int, fields[1:4])
    normalized = np.array(fields[4:], dtype=np.float32).reshape(height, width, channels)
    normalized /= maxval
    image = read_pfm(FIXTURES / f"{name}-{endian}-scale-{scale}.pfm")
    # Netpbm's writer stores normalized * scale; justPFM applies scale again.
    # This deliberate convention difference is documented in fixtures/README.md.
    expected = normalized * float(scale) ** 2
    assert image.shape == (height, width, channels)
    assert image.dtype == np.dtype(dtype)
    np.testing.assert_array_equal(image, expected)
